/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pwi' at '07.04.16 10:30' with Gradle 2.6
 *
 * @author pwi, @date 07.04.16 10:30
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
